spring.application.name=service
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/inventory
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres
management.endpoints.web.exposure.include=health,info,metrics
resilience4j.retry.instances.inventoryRetry.max-attempts=3
resilience4j.retry.instances.inventoryRetry.wait-duration=500ms
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer